### PR TITLE
JavaScript & jQuery cleanup

### PR DESCRIPTION
**Pull request by kasimi**
I have done some refactoring of mChat's JavaScript code as it was slightly outdated. :wink: 
1. Various smaller code improvements, for example:
   -  Removed `hasClass()` checks, as `removeClass()` has no effect if the selected elements don't have given CSS class.
     
     ``` javascript
      if ($('#mChatSessMess').hasClass('mchat-alert')){
          $('#mChatSessMess').removeClass('mchat-alert');
      }
      // becomes
      $('#mChatSessMess').removeClass('mchat-alert');
     ```
   - Removed redundant use of callbacks.
     
     ``` javascript
      setInterval(function(){
          mChat.refresh()
      }, mChatRefresh);
      // becomes
      setInterval(mChat.refresh, mChatRefresh);
     ```
2. In `mchat_body.html` mChat had declared all its variables globally. This has been changed so that they are all added to an `mChat = {}` object, resulting in less pollution of the global scope.
3. Depending on whether new messages are added at the top or bottom within the mChat container, `mchat_ajax_mini_top.js` or `mchat_ajax_mini.js` were included. Apart from very few lines of code, these two files are identical. They have been merged to a single file `mchat.js`. A flag `messagesTop` for the position of new messages has been added to the global `mChat` object which is used in `mchat.js` to handle the different cases.
4. `mchat.min.js` has been added which is the minified version of `mchat.js`. `mchat.min.js` is included in `mchat_body.html`, while `mchat.js` is not. The latter can be used for debugging and future code changes.

### CODE REVIEW

**Comment by dmzx** [comment]
kasimi just to be sure other PR you need also ? 
Many thanks for your time and code clean up :P

**Comment by kasimi** [comment]
Yes, I'd recommend merging the other one as well. They kind of depend on each other, but there's an easy fix to make this one work without the other one.

**Comment by dmzx** [comment]
cannot merge this one can you make request again?

**Comment by kasimi** [comment]
I updated the PR branch, hope it works now.

**Comment by dmzx** [comment]
Just a question.(nothing to do with above :P)
kasimi the mchat works now if you edit/delete a message the other will see it only after refresh page.
Do you have an quick idea how to make this automatic?

**Comment by kasimi** [comment]
I think the solution is not easy. With the current code, a client sends its latest message ID to the server and the server checks if there are any messages with a higher ID. For the server to be able to notify the client that an older message has been deleted, it would need to know _all_ IDs of the messages that the client has. I will look into it when I have a free moment. :blush:

**Comment by dmzx** [comment]
That would be great, js is not my main thing ;)
Updated to latest version on the github.

**Pull request merged**
