### PR TITLE
use tables correctly in most places

### PR DESCRIPTION
**Pull request by rmcgirr83**

### CODE REVIEW

**Comment by dmzx** [comment]
Will check it Rich, need to update also acp_mchat_module.php

**Comment by rmcgirr83** [comment]
That will require more work as you can not include the tables needed as it is currently written.  You would need an acp controller for that.  For example take a look at my [nationalflags](https://github.com/RMcGirr83/phpBB-3.1-nationalflags) extension.

**Comment by dmzx** [comment]
Got the tables in place, now checking the acp_mchat_module with the acp controller like you use in nationalflags

**Comment by dmzx** [comment]
got the admin_controller.php also in now!

**Pull request closed without merging**
